### ISSUE TITLE
fixed simple typo

### ISSUE THREAD

**Issue by Arfey** [tailhook/vagga-docker#11]
```
Mishas-MacBook-Pro:vagga_test mishagavela$ vagga run
Traceback (most recent call last):
  File "/usr/local/bin/vagga", line 11, in <module>
    load_entry_point('vagga-docker==0.1', 'console_scripts', 'vagga')()
  File "/usr/local/lib/python3.6/site-packages/vagga_docker/main.py", line 49, in main
    vagga.network_container = network.check_container(vagga, cli)
  File "/usr/local/lib/python3.6/site-packages/vagga_docker/network.py", line 15, in check_container
    if not _validate_container(container_name, ports, cli):
  File "/usr/local/lib/python3.6/site-packages/vagga_docker/network.py", line 46, in _validate_container
    extra.add(num)
AttributeError: 'dict' object has no attribute 'add'
```

https://github.com/tailhook/vagga-docker/blob/master/vagga_docker/network.py#L36

Just replace extra = {} to extra = set()

**Comment by Arfey** [comment]
fix https://github.com/tailhook/vagga-docker/pull/12

**Comment by Arfey** [comment]
Guys, you added CI without .travis.yml
Please merge my "big fix" because i can't use some else port except 8080
